config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {registrations: "user/registrations",
    sessions: "user/sessions", passwords: "user/passwords"}

  devise_for :admin, controllers: {sessions: "admin/sessions",
    passwords: "admin/passwords"}

  devise_scope :admin do
    get "admin/login", to: "admin/sessions#new"
    get "admin/logout", to: "admin/sessions#destroy"
  end

  devise_scope :user do
    get "login", to: "user/sessions#new"
    get "logout", to: "user/sessions#destroy"
    get "register", to: "user/registrations#new"
  end

  root to: "landing/landings#index", as: :user_root
  scope module: "landing" do
    resource :landings do
      collection do
        post "subscrible"
      end
    end
  end

  scope module: "user" do
    resources :users
    get "/faq", to: "faqs#index"
    get "/profile", to: "users#show"
    get "/change_password", to: "users#change_password"
    put "/change_password", to: "users#change_password"
    get "/dashboard", to: "dashboards#index"
    get "/referrals", to: "referrals#index"
    get "/buy_tokens", to: "buy_tokens#index"
    resources :verifies, only: [:index, :update]
  end

  scope module: "admin", path: "admin", as: :admin do
    resources :admins
    get "/dashboard", to: "dashboards#index"
    get "/stages", to: "stages#index"
    get "/subscribles", to: "subscribles#index"
    resource :stages do
      collection do
        post "create"
        get "load_data"
      end
    end
    resources :images
  end
  get '*path' => redirect('/')
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable,
    :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  enum image_type: {img_about: 1, img_solution_top: 2, img_solution_bot: 3,
    img_document: 4, img_app: 5, img_about_coin: 6, img_token_stats: 7}

  validates :image, presence: true
end

app/models/stage.rb
class Stage < ApplicationRecord

  # ATTR = [:stage_type, :start_register, :end_register, :end_subcrible, :start_subcrible,
  #   :end_ended, :start_date_1, :end_date_1, :coin_1, :coin_2, :start_date_2, :end_date_2]
  #
  ATTR_DATE = ["start_date_1", "end_date_1", "start_date_2", "end_date_2"];

  enum stage_type: {subscrible: 1, register: 2, buy_coin: 3, ended: 4}

  validates :stage_type, presence: true
  # validates  :start_subcrible, :end_subcrible, presence: true, if: :is_subcrible
  # validates  :start_register, :end_register, presence: true, if: :is_register
  # validates  :end_ended, presence: true, if: :is_ended
  validates  :start_date_1, :end_date_1, :coin_1, :coin_2, :start_date_2,
    :end_date_2, :progess, presence: true, if: :is_buy_coin
  validate :end_date_more_start, if: :is_buy_coin

  class << self
    def enums_for_select name
      send(name).map do |key, _|
        {
          id: key,
          name: I18n.t("enum_label.#{name}.#{key}"),
          re_name: I18n.t("enum_label.#{name}.re_#{key}")
        }
      end
    end
  end

  ATTR_DATE.each do |key|
    define_method("time_" + key) {self.send(key)&.strftime("%d/%m/%Y %H:%M %p")}
  end

  private
  def is_buy_coin
    self.buy_coin?
  end

  def is_register
    self.register?
  end

  def is_subscrible
    self.subscrible?
  end

  def is_ended
    self.ended?
  end

  def end_date_more_start
    if self.end_date_1 && self.start_date_1  && self.end_date_1 < self.start_date_1
      errors.add :end_date_1, "Must be greater than the start date"
    end
    if self.end_date_2 && self.start_date_2 && self.end_date_2 < self.start_date_2
      errors.add :end_date_2, "Must be greater than the start date"
    end
    if self.start_date_2 && self.end_date_1 && self.start_date_2 < self.end_date_1
      errors.add :start_date_2, "Must be greater than the stage PreSale"
    end
  end
end

app/models/subrible.rb
class Subrible < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_format_of :email,
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_format_of :email,
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/
end

app/models/subscrible.rb
class Subscrible < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  attr_accessor :is_verify_profile

  ATTR = [:email, :password, :password_confirmation, :first_name, :last_name,
    :country_id, :city]

  validates :first_name, :last_name, :country_id, :city, presence: true,
    if: :is_verify_profile

  belongs_to :country, optional: true

  scope :by_referral, -> id {where ref_id: id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  before_action :load_setting

  def load_setting
    @admin_setting = Stage.first
    @stage = @admin_setting&.stage_type
  end

  private

  def layout_by_resource
    if devise_controller? && resource_name == :user
      "devise_user"
    elsif devise_controller? && resource_name == :admin
      "devise_admin"
    else
      "application"
    end
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admin/stages_helper.rb
module Admin::StagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing/landings_helper.rb
module Landing::LandingsHelper
end

app/helpers/user/buy_tokens_helper.rb
module User::BuyTokensHelper
end

app/helpers/user/referrals_helper.rb
module User::ReferralsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/user/verifies_helper.rb
module User::VerifiesHelper
end

app/views/layouts/admins/_footer.html.erb
<footer class="clearfix">
  <div class="pull-right">
    Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://goo.gl/vNS3I" target="_blank">pixelcave</a>
  </div>
  <div class="pull-left">
    <span id="year-copy"></span> &copy; <a href="http://goo.gl/TDOSuC" target="_blank">ProUI 2.1</a>
  </div>
</footer>

app/views/layouts/admins/_header.html.erb
<header class="navbar navbar-default">
  <ul class="nav navbar-nav-custom">
    <li>
      <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');">
      <i class="fa fa-bars fa-fw"></i>
      </a>
    </li>
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
      <i class="gi gi-settings"></i>
      </a>
      <ul class="dropdown-menu dropdown-custom dropdown-options">
        <li class="dropdown-header text-center">Header Style</li>
        <li>
          <div class="btn-group btn-group-justified btn-group-sm">
            <a href="javascript:void(0)" class="btn btn-primary" id="options-header-default">Light</a>
            <a href="javascript:void(0)" class="btn btn-primary" id="options-header-inverse">Dark</a>
          </div>
        </li>
        <li class="dropdown-header text-center">Page Style</li>
        <li>
          <div class="btn-group btn-group-justified btn-group-sm">
            <a href="javascript:void(0)" class="btn btn-primary" id="options-main-style">Default</a>
            <a href="javascript:void(0)" class="btn btn-primary" id="options-main-style-alt">Alternative</a>
          </div>
        </li>
        <li class="dropdown-header text-center">Main Layout</li>
        <li>
          <button class="btn btn-sm btn-block btn-primary" id="options-header-top">Fixed Side/Header (Top)</button>
          <button class="btn btn-sm btn-block btn-primary" id="options-header-bottom">Fixed Side/Header (Bottom)</button>
        </li>
        <li class="dropdown-header text-center">Footer</li>
        <li>
          <div class="btn-group btn-group-justified btn-group-sm">
            <a href="javascript:void(0)" class="btn btn-primary" id="options-footer-static">Default</a>
            <a href="javascript:void(0)" class="btn btn-primary" id="options-footer-fixed">Fixed</a>
          </div>
        </li>
      </ul>
    </li>
  </ul>
  <!-- Search Form -->
  <form action="page_ready_search_results.html" method="post" class="navbar-form-custom" role="search">
    <div class="form-group">
      <input type="text" id="top-search" name="top-search" class="form-control" placeholder="Search..">
    </div>
  </form>
  <ul class="nav navbar-nav-custom pull-right">
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
      <%= image_tag "avatar.jpg" %> <i class="fa fa-angle-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
        <li class="dropdown-header text-center">Account</li>
        <li class="divider"></li>
        <li>
          <a href="page_ready_user_profile.html">
          <i class="fa fa-user fa-fw pull-right"></i>
          Profile
          </a>
          <a href="#modal-user-settings" data-toggle="modal">
          <i class="fa fa-cog fa-fw pull-right"></i>
          Settings
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="page_ready_lock_screen.html"><i class="fa fa-lock fa-fw pull-right"></i> Lock Account</a>
          <a href="<%= admin_logout_path%>"><i class="fa fa-ban fa-fw pull-right"></i> Logout</a>
        </li>
      </ul>
    </li>
  </ul>
</header>

app/views/layouts/admins/_sidebar.html.erb
<div id="sidebar">
  <div class="sidebar-scroll">
    <div class="sidebar-content">
      <a href="index.html" class="sidebar-brand">
      <i class="material-icons" style="font-size: 20px; color: red">all_inclusive</i><strong>NEETs</strong>Team
      </a>
      <div class="sidebar-section sidebar-user clearfix">
        <div class="sidebar-user-avatar">
          <a href="page_ready_user_profile.html">
          <%= image_tag "avatar.jpg" %>
          </a>
        </div>
        <div class="sidebar-user-name">John Doe</div>
        <div class="sidebar-user-links">
          <a href="page_ready_user_profile.html" data-toggle="tooltip" data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>
          <a href="page_ready_inbox.html" data-toggle="tooltip" data-placement="bottom" title="Messages"><i class="gi gi-envelope"></i></a>
          <a href="#modal-user-settings" data-toggle="modal" class="enable-tooltip" data-placement="bottom" title="Settings"><i class="gi gi-cogwheel"></i></a>
          <a href="login.html" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="gi gi-exit"></i></a>
        </div>
      </div>
      <ul class="sidebar-nav">
        <li>
          <a href="dashboard" class=" active"><i class="gi gi-stopwatch sidebar-nav-icon"></i>Dashboard</a>
        </li>
        <li class="sidebar-header">
          <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-settings"></i></a></span>
          <span class="sidebar-header-title">Site Setting</span>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-user sidebar-nav-icon"></i>User Interface</a>
          <ul>
            <li>
              <a href="stages">Time Stage</a>
            </li>
            <li>
              <a href="images">Landing Image</a>
            </li>
          </ul>
        </li>
        <li class="sidebar-header">
          <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-settings"></i></a></span>
          <span class="sidebar-header-title">Master Manager</span>
        </li>
        <li>
          <a href="subscribles"><i class="fa fa-envelope-o sidebar-nav-icon"></i>Subscrible</a>
        </li>
   <!--      <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-notes_2 sidebar-nav-icon"></i>User Manager</a>
          <ul>
            <li>
              <a href="page_forms_general.html">General</a>
            </li>
            <li>
              <a href="page_forms_components.html">Components</a>
            </li>
            <li>
              <a href="page_forms_validation.html">Validation</a>
            </li>
            <li>
              <a href="page_forms_wizard.html">Wizard</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-calendar sidebar-nav-icon"></i>Schedule</a>
          <ul>
            <li>
              <a href="page_tables_general.html">General</a>
            </li>
            <li>
              <a href="page_tables_responsive.html">Responsive</a>
            </li>
            <li>
              <a href="page_tables_datatables.html">Datatables</a>
            </li>
          </ul>
        </li>
        <li class="sidebar-header">
          <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-settings"></i></a></span>
          <span class="sidebar-header-title">Admin Manager</span>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="fa fa-lock sidebar-nav-icon"></i>Change Password</a>
          <ul>
            <li>
              <a href="#" class="sidebar-nav-submenu"><i class="fa fa-angle-left sidebar-nav-indicator"></i>3 Level Menu</a>
              <ul>
                <li>
                  <a href="#">Link 1</a>
                </li>
                <li>
                  <a href="#">Link 2</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="page_comp_maps.html">Maps</a>
            </li>
            <li>
              <a href="page_comp_charts.html">Charts</a>
            </li>
            <li>
              <a href="page_comp_gallery.html">Gallery</a>
            </li>
            <li>
              <a href="page_comp_carousel.html">Carousel</a>
            </li>
            <li>
              <a href="page_comp_calendar.html">Calendar</a>
            </li>
            <li>
              <a href="page_comp_animations.html">CSS3 Animations</a>
            </li>
            <li>
              <a href="page_comp_syntax_highlighting.html">Syntax Highlighting</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-brush sidebar-nav-icon"></i>Ready Pages</a>
          <ul>
            <li>
              <a href="#" class="sidebar-nav-submenu"><i class="fa fa-angle-left sidebar-nav-indicator"></i>Errors</a>
              <ul>
                <li>
                  <a href="page_ready_400.html">400</a>
                </li>
                <li>
                  <a href="page_ready_401.html">401</a>
                </li>
                <li>
                  <a href="page_ready_403.html">403</a>
                </li>
                <li>
                  <a href="page_ready_404.html">404</a>
                </li>
                <li>
                  <a href="page_ready_500.html">500</a>
                </li>
                <li>
                  <a href="page_ready_503.html">503</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#" class="sidebar-nav-submenu"><i class="fa fa-angle-left sidebar-nav-indicator"></i>Get Started</a>
              <ul>
                <li>
                  <a href="page_ready_blank.html">Blank</a>
                </li>
                <li>
                  <a href="page_ready_blank_alt.html">Blank Alternative</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="page_ready_search_results.html">Search Results (4)</a>
            </li>
            <li>
              <a href="page_ready_article.html">Article</a>
            </li>
            <li>
              <a href="page_ready_user_profile.html">User Profile</a>
            </li>
            <li>
              <a href="page_ready_contacts.html">Contacts</a>
            </li>
            <li>
              <a href="#" class="sidebar-nav-submenu"><i class="fa fa-angle-left sidebar-nav-indicator"></i>e-Learning</a>
              <ul>
                <li>
                  <a href="page_ready_elearning_courses.html">Courses</a>
                </li>
                <li>
                  <a href="page_ready_elearning_course_lessons.html">Course - Lessons</a>
                </li>
                <li>
                  <a href="page_ready_elearning_course_lesson.html">Course - Lesson Page</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#" class="sidebar-nav-submenu"><i class="fa fa-angle-left sidebar-nav-indicator"></i>Message Center</a>
              <ul>
                <li>
                  <a href="page_ready_inbox.html">Inbox</a>
                </li>
                <li>
                  <a href="page_ready_inbox_compose.html">Compose Message</a>
                </li>
                <li>
                  <a href="page_ready_inbox_message.html">View Message</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="page_ready_chat.html">Chat</a>
            </li>
            <li>
              <a href="page_ready_timeline.html">Timeline</a>
            </li>
            <li>
              <a href="page_ready_tickets.html">Tickets</a>
            </li>
            <li>
              <a href="page_ready_tasks.html">Tasks</a>
            </li>
            <li>
              <a href="page_ready_faq.html">FAQ</a>
            </li>
            <li>
              <a href="page_ready_pricing_tables.html">Pricing Tables</a>
            </li>
            <li>
              <a href="page_ready_invoice.html">Invoice</a>
            </li>
            <li>
              <a href="page_ready_forum.html">Forum (3)</a>
            </li>
            <li>
              <a href="#" class="sidebar-nav-submenu"><i class="fa fa-angle-left sidebar-nav-indicator"></i>Login, Register &amp; Lock</a>
              <ul>
                <li>
                  <a href="login.html">Login</a>
                </li>
                <li>
                  <a href="login_full.html">Login (Full Background)</a>
                </li>
                <li>
                  <a href="login_alt.html">Login 2</a>
                </li>
                <li>
                  <a href="login.html#reminder">Password Reminder</a>
                </li>
                <li>
                  <a href="login_alt.html#reminder">Password Reminder 2</a>
                </li>
                <li>
                  <a href="login.html#register">Register</a>
                </li>
                <li>
                  <a href="login_alt.html#register">Register 2</a>
                </li>
                <li>
                  <a href="page_ready_lock_screen.html">Lock Screen</a>
                </li>
                <li>
                  <a href="page_ready_lock_screen_alt.html">Lock Screen 2</a>
                </li>
              </ul>
            </li>
          </ul>
        </li> -->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/admins/_sidebar_alt.html.erb
<div id="sidebar-alt">
  <div class="sidebar-scroll">
    <div class="sidebar-content">
    </div>
  </div>
</div>

app/views/layouts/admins/_user_setting_modal.html.erb
<div id="modal-user-settings" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h2 class="modal-title"><i class="fa fa-pencil"></i> Settings</h2>
      </div>
      <div class="modal-body">
        <form action="index.html" method="post" enctype="multipart/form-data" class="form-horizontal form-bordered" onsubmit="return false;">
          <fieldset>
            <legend>Vital Info</legend>
            <div class="form-group">
              <label class="col-md-4 control-label">Username</label>
              <div class="col-md-8">
                <p class="form-control-static">Admin</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-email">Email</label>
              <div class="col-md-8">
                <input type="email" id="user-settings-email" name="user-settings-email" class="form-control" value="admin@example.com">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-notifications">Email Notifications</label>
              <div class="col-md-8">
                <label class="switch switch-primary">
                <input type="checkbox" id="user-settings-notifications" name="user-settings-notifications" value="1" checked>
                <span></span>
                </label>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <legend>Password Update</legend>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-password">New Password</label>
              <div class="col-md-8">
                <input type="password" id="user-settings-password" name="user-settings-password" class="form-control" placeholder="Please choose a complex one..">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-repassword">Confirm New Password</label>
              <div class="col-md-8">
                <input type="password" id="user-settings-repassword" name="user-settings-repassword" class="form-control" placeholder="..and confirm it!">
              </div>
            </div>
          </fieldset>
          <div class="form-group form-actions">
            <div class="col-xs-12 text-right">
              <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-sm btn-primary">Save Changes</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>