config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {registrations: "user/registrations",
    sessions: "user/sessions", passwords: "user/passwords"}

  devise_for :admin, controllers: {sessions: "admin/sessions",
    passwords: "admin/passwords"}

  devise_scope :admin do
    get "admin/login", to: "admin/sessions#new"
    get "admin/logout", to: "admin/sessions#destroy"
  end

  devise_scope :user do
    get "login", to: "user/sessions#new"
    get "logout", to: "user/sessions#destroy"
    get "register", to: "user/registrations#new"
  end

  root to: "landing/landings#index", as: :user_root
  scope module: "landing" do
    resource :landings do
      collection do
        post "subscrible"
      end
    end
  end

  scope module: "user" do
    resources :users
    get "/faq", to: "faqs#index"
    get "/profile", to: "users#show"
    get "/change_password", to: "users#change_password"
    put "/change_password", to: "users#change_password"
    get "/dashboard", to: "dashboards#index"
    get "/referrals", to: "referrals#index"
    get "/buy_tokens", to: "buy_tokens#index"
    resources :verifies, only: [:index, :update]
  end

  scope module: "admin", path: "admin", as: :admin do
    resources :admins
    get "/dashboard", to: "dashboards#index"
    get "/stages", to: "stages#index"
    get "/subscribles", to: "subscribles#index"
    resource :stages do
      collection do
        post "create"
        get "load_data"
      end
    end
    resources :images
  end
  get '*path' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  attr_accessor :is_verify_profile

  ATTR = [:email, :password, :password_confirmation, :first_name, :last_name,
    :country_id, :city]

  validates :first_name, :last_name, :country_id, :city, presence: true,
    if: :is_verify_profile

  belongs_to :country, optional: true

  scope :by_referral, -> id {where ref_id: id}
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::AdminsController

  def index
  end
end

app/controllers/user/buy_tokens_controller.rb
class User::BuyTokensController < User::UserManagersController
  def index
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < User::UserManagersController
  def index
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    user = User.find_by email: params[:user][:email]
    user&.send_reset_password_instructions
    render json: {
      status: user.present?,
      errors: "User not available. Please register",
      message_success: t("devise.passwords.send_instructions"),
      html: render_to_string(partial: "send_mail_success")
    }
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    user = User.reset_password_by_token(resource_params)
    status = user && user.errors.empty?
    render json: {
      status: status,
      errors: user&.errors&.full_messages || ["Reset password token is invalid"],
      redirect_path: login_path
    }
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/referrals_controller.rb
class User::ReferralsController < User::UserManagersController

  def index
    @users = User.by_referral current_user.id
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    user = User.new params_user.merge(token_ref: User.generate_unique_secure_token)
    user.ref_id = User.find_by(token_ref: params[:token_ref])&.id
    status = user.save
    user.send_confirmation_instructions if status
    render json: {
      status: status,
      errors: user.errors.full_messages,
      html: render_to_string(partial: "register_success"),
      message_success: "Register successfully"
    }
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  def params_user
    params.require(:user).permit(User::ATTR)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  respond_to :json
end

app/controllers/user/user_managers_controller.rb
class User::UserManagersController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  layout "user_manager"

  def index

  end
end

app/controllers/user/users_controller.rb
class User::UsersController < User::UserManagersController
  def index
    redirect_to user_path current_user
  end

  def show
  end

  def change_password
    @user = current_user
    return unless request.xhr?
    status = @user.update_with_password password_params
    bypass_sign_in @user if status
    render json: {
      status: status,
      errors: @user.errors.full_messages,
      message_success: "Your password has been changed"
    }
  end

  private
  def password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation);
  end
end

app/controllers/user/verifies_controller.rb
class User::VerifiesController < User::UserManagersController
  before_action :load_user

  def index; end

  def update
    status_password = @user.valid_password?(user_params[:password])
    @user.assign_attributes user_params.except(:password)
    status = @user.save if status_password
    @user.errors.add :password, "is invalid" unless status_password
    render json: {
      status: status && status_password,
      errors: @user.errors.full_messages,
      message_success: "Your profile has been update"
    }
  end

  private
  def load_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(User::ATTR - [:email]).merge(is_verify_profile: true)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    user = User.find_by email: params[:user][:email]
    user&.send_reset_password_instructions
    render json: {
      status: user.present?,
      errors: "User not available. Please register",
      message_success: t("devise.passwords.send_instructions"),
      html: render_to_string(partial: "send_mail_success")
    }
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    user = User.reset_password_by_token(resource_params)
    status = user && user.errors.empty?
    render json: {
      status: status,
      errors: user&.errors&.full_messages || ["Reset password token is invalid"],
      redirect_path: login_path
    }
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    user = User.new params_user.merge(token_ref: User.generate_unique_secure_token)
    user.ref_id = User.find_by(token_ref: params[:token_ref])&.id
    status = user.save
    user.send_confirmation_instructions if status
    render json: {
      status: status,
      errors: user.errors.full_messages,
      html: render_to_string(partial: "register_success"),
      message_success: "Register successfully"
    }
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  def params_user
    params.require(:user).permit(User::ATTR)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :json
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/user/buy_tokens_helper.rb
module User::BuyTokensHelper
end

app/helpers/user/referrals_helper.rb
module User::ReferralsHelper
end

app/helpers/user/user_managers_helper.rb
module User::UserManagersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/user/verifies_helper.rb
module User::VerifiesHelper
end

app/views/user/dashboards/index.html.erb
<div class="flex header-bar">
  <h3 class="title">Dashboard</h3>
  <a href="#"><i class="material-icons">help</i></a>
</div>
<hr class="mt15">
<div class="card mt15">
  <div class="card-content">
    <p><i class="material-icons" style="color: red">warning</i> Your account is not
      <%= link_to "verified", verifies_path%></p>
    <div class="row">
      <div class="col-md-4" align="center">
        <h5 class="fw400 mt0">Your NEET balance</h5>
        <br>
        <h4><span class="cl-lightcoral" style="font-size: 35px">5000</span> NEET</h4>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-7 text-center coin-tranfer">
        <div class="row neet-rate" align="center">
          <i class="fa fa-calculator"></i>
          <div class="row">
            <div class="col-sm-2"></div>
            <div class="form-group col-sm-4">
              <label for="inpETH" class="cl-lightcoral">ETH</label>
              <input type="email" class="form-control" id="inpETH" aria-describedby="emailHelp" value="0">
            </div>
            <div class="form-group col-sm-4">
              <label for="outNEET" class="cl-lightcoral">NEET</label>
              <input readonly="true" value="0" disabled="true" type="email" class="form-control" id="outNEET" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row" align="center">
      <button type="button" data-toggle="modal" data-target="#buyToken" class="btn btn-lightcoral">Buy Now</button>
    </div>
  </div>
</div>
<hr class="mt15">

<div class="modal fade" id="buyToken" tabindex="-1" role="dialog"
  aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <div class="row btn-buy-token" align="center">
          <div class="col-md-6">
            <a class="btn btn-lightcoral">Pay with ETH</a>
            <div class="row bd-right-solid">
              <div class="form-group">
                <label for="address-wallet" class="col-control-label col-sm-1" for="address-wallet">
                  <i class="material-icons" style="color: lightcoral">account_balance_wallet</i>
                </label>
                <div class="col-sm-7">
                  <input type="text" readonly="true" class="form-control" id="address-wallet" value="<%= current_user.token_ref %>">
                </div>
              </div>
            </div>
            <div class="row bd-right-solid" style="padding-right: 5px">
              <div class="card ">
                <div class="card-header" style="background-color: lightgreen;">
                  <span class="badge badge-info">Info</span>
                  If you provide payment to this address atf tokens will be automatically sent to the eth address that you have specified
                </div>
                <div class="card-body" align="left">
                  <div style="padding-left: 5px;">
                    <p>1. If you still dont have an ETH wallet, You can create it at myethwallet.com</p>
                    <p>2. Copy the address and paste it into your application to send ETH</p>
                    <p>3. User the wallet that you have previously added to your account</p>
                    <p>4. Recommended parameters are the Gas Limit of 20000 and Gas price of 20-79 Gwei</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <a class="btn btn-lightcoral">Pay with Visa/Master card</a>
            <div class="row">
              This function will comming soon
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>